
modLoader="javafml" #required
loaderVersion="${loader_version_range}" #required
license="${mod_license}"
[[mods]] #required
modId="${mod_id}" #required
version="${mod_version}" #required
displayName="${mod_name}" #required
authors="${mod_authors}" #optional
description='''${mod_description}'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #required
    required=true #required
    versionRange="${neo_version_range}" #required
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    required=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"